# Generated by Django 2.0.7 on 2018-09-07 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('answer_1', models.CharField(max_length=180)),
                ('answer_2', models.CharField(max_length=180)),
                ('answer_3', models.CharField(max_length=180)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nationality')),
                ('question_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_1', to='api.Question')),
                ('question_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_2', to='api.Question')),
                ('question_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_3', to='api.Question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
